### ISSUE TITLE
Background images ommission

### ISSUE THREAD

**Issue by mikisharp** [benjibobs/siteclone#3]
The script should be done to recognize such a style. 
Example
style="background-image: url(images/banner.jpg)

**Comment by mikisharp** [comment]
<div class="xs-welcome-content" style="background-image: url(images/banner.jpg);">

**Comment by mikisharp** [comment]
Can someone, please sort this? style="background-image: url(images/banner.jpg)

**Comment by benjibobs** [comment]
I will be looking into fixing this starting tomorrow. It’s been a busy week for me, sorry. I’ll be sure to notify you when support for this and perhaps wider CSS related stuff is added

On 13 Jun 2019, at 14:54, mikisharp <notifications@github.com<mailto:notifications@github.com>> wrote:


Can someone, please sort this? style="background-image: url(images/banner.jpg)

**Comment by mikisharp** [comment]
Noted, I will be keen to see it. Good script. Thanks

**Comment by benjibobs** [comment]
> Noted, I will be keen to see it. Good script. Thanks

Take a look at [this commit](https://github.com/benjibobs/siteclone/commit/4600f3c31ea69d36a1b3f96e0071241968d732fd) and try the latest version with a test page and let me know if this has been sorted.

**Comment by benjibobs** [comment]
Better, complete support is now found in the latest push

**Comment by benjibobs** [comment]
INFO: This issue will be closed in 3 days if no further issues are reported. Future issues may be opened if found after this time.

**Comment by mikisharp** [comment]
The code works so well. I give it a 5 star.
