### ISSUE TITLE
Re-download of pages

### ISSUE THREAD

**Issue by mikisharp** [benjibobs/siteclone#4]
Where the href value is an ID tag, eg  href='index.html#contact'
The system downloads index.html and index#contact.
I how can this be sorted?

**Comment by benjibobs** [comment]
Please test commit 76d22e3 @mikisharp

**Comment by mikisharp** [comment]
It works,
Just to ask what does this part do? 
`textFiles = ["css", "js", "html", "php", "json"]
print('Scanning for CSS based url(x) references...')

for subdir, dirs, files in os.walk(base_path):
	for file in files:
		
		if file == ".DS_Store" or file.split(".")[-1] not in textFiles:
			continue

		f = open(os.path.join(subdir, file), 'r', 'utf-8')
		
		content = f.read()
		if "url(" in content:
			arr = content.split("url(")
			iterations = len(arr) - 1
			i = 1
			for x in range(iterations):
				path = arr[i].split(")")[0]
				download(path)
				i += 1`

**Comment by benjibobs** [comment]
> It works,
> If I may ask what does this part do? :
> 
> `textFiles = ["css", "js", "html", "php", "json"]
> print('Scanning for CSS based url(x) references...')
> 
> for subdir, dirs, files in os.walk(base_path):
> for file in files:
> 
> ```
> 	if file == ".DS_Store" or file.split(".")[-1] not in textFiles:
> 		continue
> 
> 	f = open(os.path.join(subdir, file), 'r', 'utf-8')
> 	
> 	content = f.read()
> 	if "url(" in content:
> 		arr = content.split("url(")
> 		iterations = len(arr) - 1
> 		i = 1
> 		for x in range(iterations):
> 			path = arr[i].split(")")[0]
> 			download(path)
> 			i += 1`
> ```

This code reads all files with the specified filetype in order to find links to resources inside url() rags (such as background images etcetera). Maybe isn’t the best way to go about it, but it essentially adds support for resources only referenced in external css files
