### ISSUE TITLE
Ignores Icons in class and images inside other tags

### ISSUE THREAD

**Issue by mikisharp** [benjibobs/siteclone#5]
The code works so well, the only issue is that it overlooks some elements hidden in other tags. eg
`<figure class="icon"><img src="images/myphoto.png" alt=""></figure>` and
`<li><a href="#"><img src="images/partner.jpg" class="img-fluid" alt=""></a></li>`
Or icons in class section eg
`<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>`

**Comment by benjibobs** [comment]
The icons in the class tag are from font awesome. They should show because technically speaking the script should be cloning any local copies of that library (hardlinked copies are unaffected)

I will look into both issues. Thank you for your contributions towards testing (and breaking!) this script :)

**Comment by mikisharp** [comment]
Sure the icons should load from font awesome, Please check the other issue. I will be happy to test it. Thank you.

**Comment by mikisharp** [comment]
Is there any progress with this?
`<figure class="icon"><img src="images/myphoto.png" alt=""></figure>` and
`<li><a href="#"><img src="images/partner.jpg" class="img-fluid" alt=""></a></li>`

**Comment by benjibobs** [comment]
Not yet. I've been really busy but I will still debug and fix this when I get a chance!

**Comment by mikisharp** [comment]
I solved this by adding this file extensions
".ttf", ".otf", ".woff", ".eot" They contain fonts and icons

**Comment by benjibobs** [comment]
Thanks @mikisharp!
